project_id = "mrrfgaiumikswfjtusfj"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.expire-documentation]
    verify_jwt = false
  [functions.notify-documentation-approved]
    verify_jwt = false
  [functions.generate-client-folder]
    verify_jwt = true
